### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by alexandre-mbm** [alexandre-mbm/scanip#2]
Specs for my evolution of Fing app.

- [ ] click ‒ see [OSMBrasil/paicemana](https://github.com/OSMBrasil/paicemana)

---

`~/scanip/devices.yml`
```yml
- 'xx:xx:xx:xx:xx:xx'
  - seen: 2017-04-17 16:51:42 -03
  - type: desktop
  - ip: 
    - 192.168.0.10
    - 192.168.0.34
  - name:
    - RE073
    - LG TV
    - 32LN570B
  - vendor: 
    - LG
    - LG Electronics
  - os:
    - Android
    - Android 5.0
    - FTP
  - lock:
    - name: false
    - vendor: true
    - os: false
- 'xx:xx:xx:xx:xx:xx'
```
- [ ] OrderedList

**names**
- hostname
- model
- upnp (device)
- upnp (name)
- netbios (name)
- netbios (function)
- bonjour (name)
- customized

**vendors**
- vendor
- vendor (mac)
- netbios (domain)
- customized

**profiles**
- os
- customized (service)

---

~~`~/scanip/history.yml`~~ → `~/scanip/records.db` / TABLE **history**

time | mac | ip | comment
-- | -- | -- | --
2017-04-17 16:51:42 -03 | xx:xx:xx:xx:xx:xx | 192.168.0.10 | 
2017-04-17 16:54:40 -03 | xx:xx:xx:xx:xx:xx | 192.168.0.12 | Quando fulano estava aqui

PK = time + mac

- [ ] SQLite
